function [fitresult, gof] = createFit_linear_tracks(x, y, ldata,inid)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 30-Aug-2014 00:21:51


%% Fit: 'untitled fit 1'.

if ldata>2
[xData, yData] = prepareCurveData( x(inid:ldata), y(inid:ldata) );
else
 [xData, yData] = prepareCurveData( x(inid:end), y(inid:end) );   
end
% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );
%  if gof.rsquare>=0.1
% Plot fit with data.
figure( 7654017);


 h=plot( fitresult, xData, yData );
 hold on
 plot (x,y,'Marker','none','LineStyle','-')

 
 
hold on ;
plot (x(ldata),y(ldata),'k*')
 legend( h, 'y vs. x', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'x' );
ylabel( 'y' );
%% Uncomment the following line to preserve the X-limits of the axes
%   xlim([0 5000]);
% % %% Uncomment the following line to preserve the Y-limits of the axes
%   ylim([-2500 2500]);
grid off
axis square
hold on
% end




